# Generated by Django 5.1.4 on 2025-01-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='accs',
        ),
    ]
