# Generated by Django 5.1.4 on 2025-01-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_user_accs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accs',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
