# Generated by Django 5.1.4 on 2025-01-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_accs_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='accs',
            new_name='Account',
        ),
    ]
