# Generated by Django 5.1.4 on 2025-02-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_event_initial_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='initial_tickets',
        ),
    ]
