# Generated by Django 5.1.4 on 2025-02-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_event_initial_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='initial_tickets',
            field=models.IntegerField(default=1),
        ),
    ]
