# Generated by Django 5.1.4 on 2025-02-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_event_initial_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='initial_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
