# Generated by Django 5.1.4 on 2025-02-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_event_initial_tickets_alter_event_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='initial_tickets',
        ),
        migrations.AddField(
            model_name='event',
            name='curr_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
