# Generated by Django 5.1.4 on 2025-02-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_sponsor_user_alter_sponsor_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(related_name='events', to='web.sponsor'),
        ),
    ]
