# Generated by Django 5.1.4 on 2025-02-05 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_event_sponsors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sponsors', to='web.event'),
        ),
    ]
