# Generated by Django 5.1.4 on 2025-02-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_survey_created_at_alter_survey_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_sold',
            field=models.IntegerField(default=0),
        ),
    ]
