# Generated by Django 5.1.4 on 2025-02-08 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_event_curr_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='web.event')),
            ],
        ),
    ]
