services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0.40-debian
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: event
      MYSQL_PASSWORD: asdfghjkl
      MYSQL_DATABASE: EVENTDB
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
